naturagr/components/core/urls.py
from django.urls import path
from . import views
app_name = 'components.core'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product/<pk>/', views.ProductView.as_view(), name='product'),
    path('add-to-cart/<pk>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<pk>/', views.remove_from_cart, name='remove-from-cart'),
    path('order-summary', views.OrderSummaryView.as_view(), name='order-summary'),
    path('reduce-quantity-item/<pk>/',
         views.reduce_quantity_item, name='reduce-quantity-item')
]

naturagr/naturagr/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('components.core.urls', namespace='core')),
    path('accounts/', include('django.contrib.auth.urls'))

]

naturagr/components/core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
# Create your models here.

CATEGORY = (
    ('C', 'Cactus'),
    ('S', 'Suculentas'),
    ('P', 'Productos Naturales'),
    ('OP', 'Otras Plantas'),
    ('AJ', 'Articulos de Jardineria')
)

LABEL = (
    ('N', 'Nuevo'),
    ('MV', 'Mas Vendidos')
)


class Item(models.Model):
    item_name = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY, max_length=2)
    label = models.CharField(choices=LABEL, max_length=2, null=True)
    description = models.TextField()

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            "pk": self.pk

        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            "pk": self.pk
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            "pk": self.pk
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity}  {self.item.item_name}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

naturagr/components/core/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import ListView, DetailView, View
from django.utils import timezone
from .models import (
    Item,
    Order,
    OrderItem
)
# Create your views here.


class HomeView(ListView):
    model = Item
    template_name = 'index.html'


class ProductView(DetailView):
    model = Item
    template_name = "product.html"


@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.items.filter(item__pk=item.pk).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "Added quantity Item")
            return redirect("components.core:product", pk=pk)
        else:
            order.items.add(order_item)
            messages.info(request, "Item added to your cart")
            return redirect("components.core:product", pk=pk)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "Item added to your cart")
        return redirect("components.core:product", pk=pk)


@login_required
def remove_from_cart(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__pk=item.pk).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order_item.delete()
            messages.info(request, "Item \"" +
                          order_item.item.item_name+"\" remove from your cart")
            return redirect("components.core:product")
        else:
            messages.info(request, "This Item not in your cart")
            return redirect("components.core:product", pk=pk)
    else:
        # add message doesnt have order
        messages.info(request, "You do not have an Order")
        return redirect("components.core:product", pk=pk)


@login_required
def reduce_quantity_item(request, pk):
    item = get_object_or_404(Item, pk=pk)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__pk=item.pk).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order_item.delete()
            messages.info(request, "Item quantity was updated")
            return redirect("core:order-summary")
        else:
            messages.info(request, "This Item not in your cart")
            return redirect("core:order-summary")
    else:
        # add message doesnt have order
        messages.info(request, "You do not have an Order")
        return redirect("core:order-summary")


class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):

        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'order_summary.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an order")
            return redirect("/")

naturagr/components/core/templates/checkout.html
{% extends 'base.html' %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block content %}

<main>
    <div class="container wow fadeIn">

        <!-- Heading -->
        <h2 class="my-5 h2 text-center">Checkout form</h2>

        <!--Grid row-->
        <div class="row">

            <!--Grid column-->
            <div class="col-md-8 mb-4">

                <!--Card-->
                <div class="card">

                    <!--Card content-->
                    <form method="POST" class="card-body">
                        {% csrf_token %}
                        <!--address-->
                        <div class="md-form mb-5">
                            {{ form.street_address }}
                            <label for="address" class="">Address</label>
                        </div>

                        <!--address-2-->
                        <div class="md-form mb-5">
                            {{ form.apartment_address }}
                            <label for="address-2" class="">Address 2 (optional)</label>
                        </div>

                        <!--Grid row-->
                        <div class="row">

                            <!--Grid column-->
                            <div class="col-lg-4 col-md-12 mb-4">
                                <label for="country">Country</label>
                                {{ form.country }}
                            </div>
                            <!--Grid column-->

                            <!--Grid column-->
                            <div class="col-lg-4 col-md-6 mb-4">

                                <label for="zip">Zip</label>
                                {{ form.zip }}
                                <div class="invalid-feedback">
                                    Zip code required.
                                </div>

                            </div>
                            <!--Grid column-->

                        </div>
                        <!--Grid row-->

                        <hr>

                        <div class="custom-control custom-checkbox">
                            <input {% if form.same_billing_address.value %}checked{% endif %} type="checkbox"
                                class="custom-control-input" name="same_billing_address" id="same-address">
                            <label class="custom-control-label" for="same-address">Shipping address is the same as my
                                billing address</label>
                        </div>
                        <div class="custom-control custom-checkbox">
                            <input {% if form.save_info.value %}checked{% endif %} type="checkbox"
                                class="custom-control-input" name="save_info" id="save-info">
                            <label class="custom-control-label" for="save-info">Save this information for next
                                time</label>
                        </div>

                        <hr>

                        <div class="d-block my-3">
                            {% for value, name in form.fields.payment_option.choices %}
                            <div class="custom-control custom-radio">
                                <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio"
                                    class="custom-control-input" required>
                                <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                            </div>
                            {% endfor %}
                        </div>

                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

                    </form>

                </div>
                <!--/.Card-->

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-4 mb-4">

                <!-- Heading -->
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your cart</span>
                    <span class="badge badge-secondary badge-pill">3</span>
                </h4>

                <!-- Cart -->
                <ul class="list-group mb-3 z-depth-1">
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">Product name</h6>
                            <small class="text-muted">Brief description</small>
                        </div>
                        <span class="text-muted">$12</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">Second product</h6>
                            <small class="text-muted">Brief description</small>
                        </div>
                        <span class="text-muted">$8</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">Third item</h6>
                            <small class="text-muted">Brief description</small>
                        </div>
                        <span class="text-muted">$5</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between bg-light">
                        <div class="text-success">
                            <h6 class="my-0">Promo code</h6>
                            <small>EXAMPLECODE</small>
                        </div>
                        <span class="text-success">-$5</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total (USD)</span>
                        <strong>$20</strong>
                    </li>
                </ul>
                <!-- Cart -->

                <!-- Promo code -->
                <form class="card p-2">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Promo code"
                            aria-label="Recipient's username" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
                        </div>
                    </div>
                </form>
                <!-- Promo code -->

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

    </div>
</main>
<!--Main layout-->

{% endblock content %}

naturagr/components/core/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<main id="main">

  <!-- ======= Hero Slider Section ======= -->
  <section id="hero-slider" class="hero-slider">
    <div class="container-md" data-aos="fade-in">
      <div class="row">
        <div class="col-12">
          <div class="swiper sliderFeaturedPosts">
            <div class="swiper-wrapper">
              <div class="swiper-slide">
                <a href="single-post.html" class="img-bg d-flex align-items-end"
                  style="background-image: url('{% static 'assets/img/post-slide-1.jpg' %}');">
                  <div class="img-bg-inner">
                    <h2>The Best Homemade Masks for Face (keep the Pimples Away)</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem neque est mollitia! Beatae
                      minima assumenda repellat harum vero, officiis ipsam magnam obcaecati cumque maxime inventore
                      repudiandae quidem necessitatibus rem atque.</p>
                  </div>
                </a>
              </div>

              <div class="swiper-slide">
                <a href="single-post.html" class="img-bg d-flex align-items-end"
                  style="background-image: url('{% static 'assets/img/post-slide-1.jpg' %}');">
                  <div class="img-bg-inner">
                    <h2>17 Pictures of Medium Length Hair in Layers That Will Inspire Your New Haircut</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem neque est mollitia! Beatae
                      minima assumenda repellat harum vero, officiis ipsam magnam obcaecati cumque maxime inventore
                      repudiandae quidem necessitatibus rem atque.</p>
                  </div>
                </a>
              </div>

              <div class="swiper-slide">
                <a href="single-post.html" class="img-bg d-flex align-items-end"
                  style="background-image: url('{% static 'assets/img/post-slide-1.jpg' %}');">
                  <div class="img-bg-inner">
                    <h2>13 Amazing Poems from Shel Silverstein with Valuable Life Lessons</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem neque est mollitia! Beatae
                      minima assumenda repellat harum vero, officiis ipsam magnam obcaecati cumque maxime inventore
                      repudiandae quidem necessitatibus rem atque.</p>
                  </div>
                </a>
              </div>

              <div class="swiper-slide">
                <a href="single-post.html" class="img-bg d-flex align-items-end"
                  style="background-image:  url('{% static 'assets/img/post-slide-1.jpg' %}');">
                  <div class="img-bg-inner">
                    <h2>9 Half-up/half-down Hairstyles for Long and Medium Hair</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem neque est mollitia! Beatae
                      minima assumenda repellat harum vero, officiis ipsam magnam obcaecati cumque maxime inventore
                      repudiandae quidem necessitatibus rem atque.</p>
                  </div>
                </a>
              </div>
            </div>
            <div class="custom-swiper-button-next">
              <span class="bi-chevron-right"></span>
            </div>
            <div class="custom-swiper-button-prev">
              <span class="bi-chevron-left"></span>
            </div>

            <div class="swiper-pagination"></div>
          </div>
        </div>
      </div>
    </div>
  </section><!-- End Hero Slider Section -->

  <!-- ======= Post Grid Section ======= -->
  <section id="posts" class="posts">
    <div class="container" data-aos="fade-up">
      <div class="row g-5">
        <div class="col-lg-4">
          <div class="post-entry-1 lg">
            <a href="single-post.html"><img src="{% static 'assets/img/post-landscape-1.jpg' %}" alt=""
                class="img-fluid"></a>
            <div class="post-meta"><span class="date">Culture</span> <span class="mx-1">&bullet;</span> <span>Jul 5th
                '22</span></div>
            <h2><a href="single-post.html">11 Work From Home Part-Time Jobs You Can Do Now</a></h2>
            <p class="mb-4 d-block">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero temporibus
              repudiandae, inventore pariatur numquam cumque possimus exercitationem? Nihil tempore odit ab minus
              eveniet praesentium, similique blanditiis molestiae ut saepe perspiciatis officia nemo, eos quae cumque.
              Accusamus fugiat architecto rerum animi atque eveniet, quo, praesentium dignissimos</p>

            <div class="d-flex align-items-center author">
              <div class="photo"><img src="{% static 'assets/img/person-1.png' %}" alt="" class="img-fluid"></div>
              <div class="name">
                <h3 class="m-0 p-0">Cameron Williamson</h3>
              </div>
            </div>
          </div>

        </div>

        <div class="col-lg-8">
          <div class="row g-8">
            <div class="col-lg-8 border-start custom-border">
              <div class="post-entry-1">
                <a href="single-post.html"><img src="{% static 'assets/img/post-landscape-2.png' %}" alt=""
                    class="img-fluid"></a>
                <div class="post-meta"><span class="date">Sport</span> <span class="mx-1">&bullet;</span> <span>Jul
                    5th '22</span></div>
                <h2><a href="single-post.html">Let’s Get Back to Work, New York</a></h2>
              </div>
              <div class="post-entry-1">
                <a href="single-post.html"><img src="{% static 'assets/img/post-landscape-5.png' %}" alt=""
                    class="img-fluid"></a>
                <div class="post-meta"><span class="date">Food</span> <span class="mx-1">&bullet;</span> <span>Jul
                    17th '22</span></div>
                <h2><a href="single-post.html">How to Avoid Distraction and Stay Focused During Video Calls?</a></h2>
              </div>
              <div class="post-entry-1">
                <a href="single-post.html"><img src="{% static 'assets/img/post-landscape-7.png' %}" alt=""
                    class="img-fluid"></a>
                <div class="post-meta"><span class="date">Design</span> <span class="mx-1">&bullet;</span> <span>Mar
                    15th '22</span></div>
                <h2><a href="single-post.html">Why Craigslist Tampa Is One of The Most Interesting Places On the
                    Web?</a></h2>
              </div>
            </div>
            <div class="col-lg-4 border-start custom-border">
              <div class="post-entry-1">
                <a href="single-post.html"><img src="{% static 'assets/img/post-landscape-3.png' %}" alt=""
                    class="img-fluid"></a>
                <div class="post-meta"><span class="date">Business</span> <span class="mx-1">&bullet;</span> <span>Jul
                    5th '22</span></div>
                <h2><a href="single-post.html">6 Easy Steps To Create Your Own Cute Merch For Instagram</a></h2>
              </div>
              <div class="post-entry-1">
                <a href="single-post.html"><img src="{% static 'assets/img/post-landscape-6.jpg' %}" alt=""
                    class="img-fluid"></a>
                <div class="post-meta"><span class="date">Tech</span> <span class="mx-1">&bullet;</span> <span>Mar 1st
                    '22</span></div>
                <h2><a href="single-post.html">10 Life-Changing Hacks Every Working Mom Should Know</a></h2>
              </div>
              <div class="post-entry-1">
                <a href="single-post.html"><img src="{% static 'assets/img/post-landscape-8.jpg' %}" alt=""
                    class="img-fluid"></a>
                <div class="post-meta"><span class="date">Travel</span> <span class="mx-1">&bullet;</span> <span>Jul
                    5th '22</span></div>
                <h2><a href="single-post.html">5 Great Startup Tips for Female Founders</a></h2>
              </div>
            </div>

          </div>
        </div>

      </div> <!-- End .row -->
    </div>
  </section> <!-- End Post Grid Section -->



</main><!-- End #main -->
{% endblock %}

naturagr/components/core/templates/order_sumary.html
{% extends 'base.html' %}

{% block content %}

<main>
    <div class="container">
        <div class="table-responsive text-nowrap">
            <h3>
                <strong>Your Cart</strong>
            </h3>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.item.item_name }}</td>
                        <td>
                            {% if order_item.item.discount_price %}
                            <del>${{ order_item.item.price}}</del>
                            ${{ order_item.item.discount_price }}
                            {% else %}
                            ${{ order_item.item.price}}
                            {% endif %}

                        </td>
                        <td>
                            <a href="{% url 'core:reduce-quantity-item' order_item.item.pk %}"><i
                                    class="fas fa-minus mr-2"></i></a>
                            {{ order_item.quantity }}
                            <a href="{% url 'core:add-to-cart' order_item.item.pk %}"><i
                                    class="fas fa-plus ml-2"></i></a>
                        </td>
                        <td>
                            {% if order_item.item.discount_price %}
                            ${{ order_item.get_discount_item_price }}
                            <span class="badge badge-success">Saved ${{ order_item.get_amount_saved }}</span>
                            {% else %}
                            ${{ order_item.get_total_item_price}}
                            {% endif %}
                            <a href="{% url 'core:remove-from-cart' order_item.item.pk %}">
                                <i class="fas fa-trash float-right text-danger"></i>
                            </a>

                        </td>
                    </tr>

                    {% empty %}
                    <tr>
                        <td colspan="5">Your Cart Empty</td>
                    </tr>

                    <tr>
                        <td colspan="5">
                            <a href="/" class="btn btn-primarsy float-right">Continue Shopping</a>
                        </td>
                    </tr>

                    {% endfor %}

                    {% if object.get_total_price %}
                    <tr>
                        <td colspan="4"><b>Total Order Price</b></td>
                        <td>${{ object.get_total_price }}</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a href="#" class="btn btn-warning float-right ml-2">Checkout</a>
                            <a href="/" class="btn btn-primary float-right">Continue Shopping</a>
                        </td>
                    </tr>

                    {% endif %}

                </tbody>
            </table>

        </div>
    </div>
</main>

{% endblock content %}

naturagr/components/core/templates/product.html
{% extends 'base.html' %}

{% block content %}

<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

        <!--Grid row-->
        <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-md-6 mb-4">

                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="img-fluid"
                    alt="">

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">

                <!--Content-->
                <div class="p-4">

                    <div class="mb-3">
                        <a href="">
                            <span class="badge purple mr-1">{{ object.get_category_display }}</span>
                        </a>
                        <a href="">
                            <span class="badge blue mr-1">{{ object.get_label_display }}</span>
                        </a>
                    </div>

                    <p class="lead">

                        {% if object.discount_price %}
                        <span class="mr-1">
                            <del>${{ object.price }}</del>
                        </span>
                        <span>${{ object.discount_price }}</span>
                        {% else %}
                        <span>${{ item.price }}</span>
                        {% endif %}

                    </p>

                    <p class="lead font-weight-bold">{{ object.item_name }}</p>

                    <p>{{ object.description }}</p>

                    {% comment %} <form class="d-flex justify-content-left">
                        <!-- Default input -->
                        <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
                        <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                            <i class="fas fa-shopping-cart ml-1"></i>
                        </button>

                    </form> {% endcomment %}

                    <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">Add to cart
                        <i class="fas fa-shopping-cart ml-1"></i>
                    </a>
                    <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">Remove From
                        cart
                        <i class="fas fa-trash ml-1"></i>
                    </a>

                </div>
                <!--Content-->

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

        <hr>

        <!--Grid row-->
        <div class="row d-flex justify-content-center wow fadeIn">

            <!--Grid column-->
            <div class="col-md-6 text-center">

                <h4 class="my-4 h4">Additional information</h4>

                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta
                    odit
                    voluptates,
                    quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-lg-4 col-md-12 mb-4">

                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid"
                    alt="">

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">

                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid"
                    alt="">

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">

                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid"
                    alt="">

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

    </div>
</main>
<!--Main layout-->

{% endblock content %}